name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      # 安装依赖
      - name: Install dependencies
        run: npm ci

      # 构建 Next.js 应用
      - name: Build Next.js app
        run: npm run build

      # 部署到 gh-pages 分支
      - name: Deploy to gh-pages branch
        run: |
          # 配置 Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 切换到 gh-pages 分支
          git fetch origin gh-pages
          git switch gh-pages || git checkout --orphan gh-pages
          
          # 清空 gh-pages 分支并复制构建结果
          git rm -rf .
          cp -r ./out/* .
          
          # 添加所有文件并推送到远程 gh-pages 分支
          git add .
          git commit -m "Deploy from main branch"
          git push origin gh-pages --force
